spring:
  profiles:
    include: dev
  application:
    name: service-ai
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.3:8848
        username: nacos
        password: nacos
server:
  port: 7010