spring:
  application:
    name: service-book
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.3:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.3:3306/library
    username: root
    password: 'Won021220'
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 7020