spring:
  application:
    name: service-book
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.3:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.3:3306/library
    username: root
    password: 'Won021220'
  rabbitmq:
    host: 192.168.0.3
    port: 5672
    username: kane
    password: Won021220
    virtual-host: /library
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 7020

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn