spring:
  cloud:
    gateway:
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
        - id: service-ai
          uri: lb://service-ai
          predicates:
            - Path=/api/ai/**
